In [1]:
import warnings
warnings.filterwarnings('ignore')

# Importando biblioteca Pandas para a criação e manipulação de DataFrames.
import pandas as pd

# Importando o Numpy.
import numpy as np

# Importando o método PLT para visualizar graficamente os dados, cálculos e regressões que aplicarmos.
import matplotlib.pylab as plt

# Importando modelos para a realização dos testes de treino.
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB

# Importando métricas de avaliações para os modelos.
from sklearn.metrics import confusion_matrix, f1_score, auc, roc_auc_score, roc_curve

# Importando o método de validação cruzada K-Fold, pontuação do modelo e o separador de dados para treino e teste.
from sklearn.model_selection import KFold, cross_val_score,train_test_split

In [2]:
# Importando dataset de dados de treino da vetorização TF:
dados_treino_tf = pd.read_csv("tweets_vetorizados_tf_novos_agrupados.csv", sep=",", header=None)
dados_treino_tf.head(5)

,0,1,2,3,4,5,6,7,8,9,...,326,327,328,329,330,331,332,333,334,335
0,NaN,11,14,20,2022,22,24,26,269,2⁰,...,voltou,voluntários,votar,votos,votou,vídeo,xandão,youtu,índios,Cluster
1,0.0,0,0,1,0,0,0,0,0,0,...,1,0,1,0,1,0,0,0,0,negative
2,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
3,2.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
4,3.0,0,1,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,negative

In [3]:
# Separação dos dados:
dados_treino_tf.columns = [dados_treino_tf.loc[0]]
dados_treino_tf = dados_treino_tf.drop(dados_treino_tf.index[[0]])
dados_treino_tf.head(5)

,NaN,11,14,20,2022,22,24,26,269,2⁰,...,voltou,voluntários,votar,votos,votou,vídeo,xandão,youtu,índios,Cluster
1,0.0,0,0,1,0,0,0,0,0,0,...,1,0,1,0,1,0,0,0,0,negative
2,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
3,2.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,negative
4,3.0,0,1,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,negative
5,4.0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,negative

In [4]:
# Importando dataset de dados de treino da vetorização IDF:
dados_treino_idf = pd.read_csv("tweets_vetorizados_idf_novos_agrupados.csv", sep=",", header=None)
dados_treino_idf.head()

# Separação dos dados:
dados_treino_idf.columns = [dados_treino_idf.loc[0]]
dados_treino_idf = dados_treino_idf.drop(dados_treino_idf.index [[0]])
dados_treino_idf.head(5)

,NaN,11.0,14.0,20.0,2022.0,22.0,24.0,26.0,269.0,2⁰,...,voltou,voluntários,votar,votos,votou,vídeo,xandão,youtu,índios,Cluster
1,0.0,NaN,NaN,0.281786,NaN,NaN,NaN,NaN,NaN,NaN,...,0.2817858340273836,NaN,0.2817858340273836,NaN,0.2817858340273836,NaN,NaN,NaN,NaN,negative
2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,negative
3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,negative
4,3.0,NaN,0.188782,NaN,NaN,0.090386,NaN,NaN,0.188782,NaN,...,NaN,0.1887824589501638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,negative
5,4.0,0.102834,NaN,NaN,NaN,0.082830,NaN,0.157122,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.1730002790668289,NaN,NaN,NaN,negative

In [5]:
# Importando dataset de dados de treino da vetorização TF_IDF:
dados_treino_tf_idf = pd.read_csv("tweets_vetorizados_tf_idf_novos_agrupados.csv", sep=",", header=None)
dados_treino_tf_idf.head()

,0,1,2,3,4,5,6,7,8,9,...,326,327,328,329,330,331,332,333,334,335
0,NaN,11.0,14.000000,20.000000,2022.0,22.000000,24.0,26.0,269.000000,2⁰,...,voltou,voluntários,votar,votos,votou,vídeo,xandão,youtu,índios,Cluster
1,0.0,0.0,0.000000,0.281786,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.2817858340273836,0.0,0.2817858340273836,0.0,0.2817858340273836,0.0,0.0,0.0,0.0,negative
2,1.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,negative
3,2.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,negative
4,3.0,0.0,0.188782,0.000000,0.0,0.090386,0.0,0.0,0.188782,0.0,...,0.0,0.1887824589501638,0.0,0.0,0.0,0.0,0.0,0.0,0.0,negative

In [6]:
# Separação dos dados:
dados_treino_tf_idf.columns = [dados_treino_tf_idf.loc[0]]
dados_treino_tf_idf = dados_treino_tf_idf.drop(dados_treino_tf_idf.index [[0]])
dados_treino_tf_idf.head(5)

,NaN,11.0,14.0,20.0,2022.0,22.0,24.0,26.0,269.0,2⁰,...,voltou,voluntários,votar,votos,votou,vídeo,xandão,youtu,índios,Cluster
1,0.0,0.000000,0.000000,0.281786,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.2817858340273836,0.0,0.2817858340273836,0.0,0.2817858340273836,0.0,0.0,0.0,0.0,negative
2,1.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,negative
3,2.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,negative
4,3.0,0.000000,0.188782,0.000000,0.0,0.090386,0.0,0.000000,0.188782,0.0,...,0.0,0.1887824589501638,0.0,0.0,0.0,0.0,0.0,0.0,0.0,negative
5,4.0,0.102834,0.000000,0.000000,0.0,0.082830,0.0,0.157122,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1730002790668289,0.0,0.0,0.0,negative

## Modelo de Regressão Logística (Logistic Regression)

### TF

In [7]:
X = dados_treino_tf.drop(['Cluster'], axis=1).values
y = dados_treino_tf['Cluster'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 4)

In [8]:
# Criação e treino do modelo de Regressão Logística:
model = LogisticRegression(penalty = 'l2', C = 1e42, solver = 'liblinear')
model.fit(X_train, y_train)
lr_pred = model.predict(X)

In [9]:
# Aplicação da validação cruzada K-Fold:
kfold_validation = KFold(10)
result = cross_val_score(model, X_test, y_test, cv = kfold_validation)

# Exibição dos resultados da validação:
print('Resultados do modelo:\n', result)
print('\nMédia dos resultados:', np.mean(result))
print('\nPredições feitas:\n', lr_pred)

Resultados do modelo:
 [0.5 0.5 1.  1.  1.  1.  1.  1.  1.  1. ]

Média dos resultados: 0.9

Predições feitas:
 ['negative' 'negative' 'negative' 'negative' 'neutral' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'neutral'
 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral'
 'neutral' 'neutral' 'neutral' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative']

In [10]:
# Criação da matriz de confusão:
print('Matriz de confusão:')
c_matrix = confusion_matrix(y, model.predict(X))
c_matrix

Matriz de confusão:

array([[34,  1,  0],
       [ 0, 11,  0],
       [ 0,  0, 14]], dtype=int64)

In [11]:
# Exibição das métricas de avaliação do modelo:
print('Revocação (Recall): ', c_matrix[0, 0] / sum(c_matrix[0, :]), '\n')
print('Precisão (Precision): ', c_matrix[0, 0] / sum(c_matrix[:, 0]), '\n')
print('Especificidade (Specificity): ', c_matrix[1, 1] / sum(c_matrix[1, :]), '\n')
print('F1 Macro: ', f1_score(y, model.predict(X), average='macro'), '\n')
print('F1 Micro: ', f1_score(y, model.predict(X), average='micro'))

Revocação (Recall):  0.9714285714285714

Precisão (Precision):  1.0

Especificidade (Specificity):  1.0

F1 Macro:  0.9806763285024154

F1 Micro:  0.9833333333333333

### IDF

In [12]:
dados_treino_idf = dados_treino_idf.replace(np.nan, 0)

In [13]:
X = dados_treino_idf.drop(['Cluster'], axis=1).values
y = dados_treino_idf['Cluster'].values

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 4)

In [15]:
# Criação e treino do modelo de Regressão Logística:
model = LogisticRegression(penalty = 'l2', C = 1e42, solver = 'liblinear')
model.fit(X_train, y_train)
lr_pred = model.predict(X)

In [16]:
# Aplicação da validação cruzada K-Fold:
kfold_validation = KFold(10)
result = cross_val_score(model, X_test, y_test, cv = kfold_validation)

# Exibição dos resultados da validação:
print('Resultados do modelo:\n', result)
print('\nMédia dos resultados:', np.mean(result))
print('\nPredições feitas:\n', lr_pred)

Resultados do modelo:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Média dos resultados: 1.0

Predições feitas:
 ['negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'neutral'
 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral'
 'neutral' 'neutral' 'neutral' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative']

In [17]:
# Criação da matriz de confusão:
print('Matriz de confusão:')
c_matrix = confusion_matrix(y, model.predict(X))
c_matrix

Matriz de confusão:

array([[35,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 14]], dtype=int64)

In [18]:
# Exibição das métricas de avaliação do modelo:
print('Revocação (Recall): ', c_matrix[0, 0] / sum(c_matrix[0, :]), '\n')
print('Precisão (Precision): ', c_matrix[0, 0] / sum(c_matrix[:, 0]), '\n')
print('Especificidade (Specificity): ', c_matrix[1, 1] / sum(c_matrix[1, :]), '\n')
print('F1 Macro: ', f1_score(y, model.predict(X), average='macro'), '\n')
print('F1 Micro: ', f1_score(y, model.predict(X), average='micro'))

Revocação (Recall):  1.0

Precisão (Precision):  1.0

Especificidade (Specificity):  1.0

F1 Macro:  1.0

F1 Micro:  1.0

### TF-IDF

In [19]:
X = dados_treino_tf_idf.drop(['Cluster'], axis=1).values
y = dados_treino_tf_idf['Cluster'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 4)

# Criação e treino do modelo de Regressão Logística:
model = LogisticRegression(penalty = 'l2', C = 1e42, solver = 'liblinear')
model.fit(X_train, y_train)
lr_pred = model.predict(X)

In [20]:
# Aplicação da validação cruzada K-Fold:
kfold_validation = KFold(10)
result = cross_val_score(model, X_test, y_test, cv = kfold_validation)

# Exibição dos resultados da validação:
print('Resultados do modelo:\n', result)
print('\nMédia dos resultados:', np.mean(result))
print('\nPredições feitas:\n', lr_pred)

Resultados do modelo:
 [0.5 1.  1.  1.  1.  1.  1.  1.  1.  1. ]

Média dos resultados: 0.95

Predições feitas:
 ['negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'neutral'
 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral'
 'neutral' 'neutral' 'neutral' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative']

In [21]:
# Criação da matriz de confusão:
print('Matriz de confusão:')
c_matrix = confusion_matrix(y, model.predict(X))
c_matrix

Matriz de confusão:

array([[35,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 14]], dtype=int64)

In [22]:
# Exibição das métricas de avaliação do modelo:
print('Revocação (Recall): ', c_matrix[0, 0] / sum(c_matrix[0, :]), '\n')
print('Precisão (Precision): ', c_matrix[0, 0] / sum(c_matrix[:, 0]), '\n')
print('Especificidade (Specificity): ', c_matrix[1, 1] / sum(c_matrix[1, :]), '\n')
print('F1 Macro: ', f1_score(y, model.predict(X), average='macro'), '\n')
print('F1 Micro: ', f1_score(y, model.predict(X), average='micro'))

Revocação (Recall):  1.0

Precisão (Precision):  1.0

Especificidade (Specificity):  1.0

F1 Macro:  1.0

F1 Micro:  1.0

## Modelo Naive Bayes

### TF

In [23]:
# Separação dos dados para teste e treino:
X = dados_treino_idf.drop(['Cluster'], axis=1).values
y = dados_treino_idf['Cluster'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)

# Criação e treino do modelo Naive Bayes:
model = MultinomialNB(alpha=0.01, fit_prior=True)
model.fit(X_train, y_train)
nb_pred = model.predict(X)

# Aplicação da validação cruzada K-Fold:
kfold_validation = KFold(10)
result = cross_val_score(model, X_test, y_test, cv = kfold_validation)

# Exibição dos resultados da validação:
print('Resultados do modelo:\n', result)
print('\nMédia dos resultados:', np.mean(result))
print('\nPredições feitas:\n', nb_pred)

Resultados do modelo:
 [0.5 0.5 1.  1.  1.  1.  1.  1.  1.  1. ]

Média dos resultados: 0.9

Predições feitas:
 ['negative' 'negative' 'negative' 'negative' 'neutral' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'neutral'
 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral'
 'neutral' 'neutral' 'neutral' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative']

In [24]:
# Aplicação da validação cruzada K-Fold:
kfold_validation = KFold(10)
result = cross_val_score(model, X_test, y_test, cv = kfold_validation)

# Exibição dos resultados da validação:
print('Resultados do modelo:\n', result)
print('\nMédia dos resultados:', np.mean(result))
print('\nPredições feitas:\n', lr_pred)

Resultados do modelo:
 [0.5 0.5 1.  1.  1.  1.  1.  1.  1.  1. ]

Média dos resultados: 0.9

Predições feitas:
 ['negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'neutral'
 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral'
 'neutral' 'neutral' 'neutral' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative']

In [25]:
# Criação da matriz de confusão:
print('Matriz de confusão:')
c_matrix = confusion_matrix(y, model.predict(X))
c_matrix

Matriz de confusão:

array([[34,  1,  0],
       [ 0, 11,  0],
       [ 0,  0, 14]], dtype=int64)

In [26]:
# Exibição das métricas de avaliação do modelo:
print('Revocação (Recall): ', c_matrix[0, 0] / sum(c_matrix[0, :]), '\n')
print('Precisão (Precision): ', c_matrix[0, 0] / sum(c_matrix[:, 0]), '\n')
print('Especificidade (Specificity): ', c_matrix[1, 1] / sum(c_matrix[1, :]), '\n')
print('F1 Macro: ', f1_score(y, model.predict(X), average='macro'), '\n')
print('F1 Micro: ', f1_score(y, model.predict(X), average='micro'))

Revocação (Recall):  0.9714285714285714

Precisão (Precision):  1.0

Especificidade (Specificity):  1.0

F1 Macro:  0.9806763285024154

F1 Micro:  0.9833333333333333

### IDF

In [27]:
dados_treino_idf = dados_treino_idf.replace(np.nan, 0)

# Separação dos dados para teste e treino:
X = dados_treino_idf.drop(['Cluster'], axis=1).values
y = dados_treino_idf['Cluster'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)

# Criação e treino do modelo Naive Bayes:
model = MultinomialNB(alpha=0.01, fit_prior=True)
model.fit(X_train, y_train)
nb_pred = model.predict(X)

# Aplicação da validação cruzada K-Fold:
kfold_validation = KFold(10)
result = cross_val_score(model, X_test, y_test, cv = kfold_validation)

# Exibição dos resultados da validação:
print('Resultados do modelo:\n', result)
print('\nMédia dos resultados:', np.mean(result))
print('\nPredições feitas:\n', nb_pred)

Resultados do modelo:
 [0.5 0.5 1.  1.  1.  1.  1.  1.  1.  1. ]

Média dos resultados: 0.9

Predições feitas:
 ['negative' 'negative' 'negative' 'negative' 'neutral' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'neutral'
 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral'
 'neutral' 'neutral' 'neutral' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative']

In [28]:
# Criação da matriz de confusão:
print('Matriz de confusão:')
c_matrix = confusion_matrix(y, model.predict(X))
c_matrix

Matriz de confusão:

array([[34,  1,  0],
       [ 0, 11,  0],
       [ 0,  0, 14]], dtype=int64)

In [29]:
# Exibição das métricas de avaliação do modelo:
print('Revocação (Recall): ', c_matrix[0, 0] / sum(c_matrix[0, :]), '\n')
print('Precisão (Precision): ', c_matrix[0, 0] / sum(c_matrix[:, 0]), '\n')
print('Especificidade (Specificity): ', c_matrix[1, 1] / sum(c_matrix[1, :]), '\n')
print('F1 Macro: ', f1_score(y, model.predict(X), average='macro'), '\n')
print('F1 Micro: ', f1_score(y, model.predict(X), average='micro'))

Revocação (Recall):  0.9714285714285714

Precisão (Precision):  1.0

Especificidade (Specificity):  1.0

F1 Macro:  0.9806763285024154

F1 Micro:  0.9833333333333333

### TF-IDF

In [30]:
# Separação dos dados para teste e treino:
X = dados_treino_tf_idf.drop(['Cluster'], axis=1).values
y = dados_treino_tf_idf['Cluster'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)

# Criação e treino do modelo Naive Bayes:
model = MultinomialNB(alpha=0.01, fit_prior=True)
model.fit(X_train, y_train)
nb_pred = model.predict(X)

# Aplicação da validação cruzada K-Fold:
kfold_validation = KFold(10)
result = cross_val_score(model, X_test, y_test, cv = kfold_validation)

# Exibição dos resultados da validação:
print('Resultados do modelo:\n', result)
print('\nMédia dos resultados:', np.mean(result))
print('\nPredições feitas:\n', nb_pred)

Resultados do modelo:
 [0.5 0.5 1.  1.  1.  1.  1.  1.  1.  1. ]

Média dos resultados: 0.9

Predições feitas:
 ['negative' 'negative' 'negative' 'negative' 'neutral' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'neutral'
 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral' 'neutral'
 'neutral' 'neutral' 'neutral' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'neutral' 'negative' 'negative' 'negative']

In [31]:
# Criação da matriz de confusão:
print('Matriz de confusão:')
c_matrix = confusion_matrix(y, model.predict(X))
c_matrix

Matriz de confusão:

array([[33,  2,  0],
       [ 0, 11,  0],
       [ 0,  0, 14]], dtype=int64)

In [32]:
# Exibição das métricas de avaliação do modelo:
print('Revocação (Recall): ', c_matrix[0, 0] / sum(c_matrix[0, :]), '\n')
print('Precisão (Precision): ', c_matrix[0, 0] / sum(c_matrix[:, 0]), '\n')
print('Especificidade (Specificity): ', c_matrix[1, 1] / sum(c_matrix[1, :]), '\n')
print('F1 Macro: ', f1_score(y, model.predict(X), average='macro'), '\n')
print('F1 Micro: ', f1_score(y, model.predict(X), average='micro'))

Revocação (Recall):  0.9428571428571428

Precisão (Precision):  1.0

Especificidade (Specificity):  1.0

F1 Macro:  0.9624183006535948

F1 Micro:  0.9666666666666667